import os
import io
import subprocess
from gtts import gTTS
import imageio_ffmpeg

DATASET_SIZE = 250
OUTPUT_DIR = "./data"
SAMPLE_RATE = 16000

SENTENCES = [
    "The cat sat on the mat",
    "I like to read books",
    "She went to the store",
    "The sun is shining bright",
    "He runs very fast",
    "We are going to the park",
    "The dog barked at the mailman",
    "It is a beautiful day",
    "Please open the door",
    "Can you help me please",
    "The bird flew over the house",
    "My favorite color is blue",
    "They are playing soccer",
    "The food tastes delicious",
    "Good morning how are you",
    "I need a glass of water",
    "The music is very loud",
    "She loves to dance",
    "He drove his car to work",
    "The flowers are blooming",
    "Turn off the light please",
    "I am learning to code",
    "The movie was really good",
    "Let us go for a walk",
    "The baby is sleeping quietly",
    "Please pass the salt",
    "The train arrives at noon",
    "I brush my teeth every day",
    "The sky is very clear tonight",
    "He wrote a letter to his friend",
    "The coffee is too hot",
    "She wears a red dress",
    "The students are studying hard",
    "I live in a small town",
    "The river flows through the valley",
    "Please sit down and relax",
    "The cake tastes very sweet",
    "He plays the guitar well",
    "We visited the museum yesterday",
    "The phone is ringing loudly",
    "I will meet you at noon",
    "The tree has green leaves",
    "She speaks three languages fluently",
    "The rain stopped in the evening",
    "He fixed the broken chair",
    "The children are laughing happily",
    "I enjoy swimming in the pool",
    "The bridge connects two cities",
    "Please write your name here",
    "The pizza is ready to eat",
    "She painted a lovely picture",
    "He reads the newspaper every morning",
    "The store closes at nine o clock",
    "I put on my warm jacket",
    "The cat climbed up the tree",

    "The teacher explained the lesson clearly",
    "I enjoy listening to soft music",
    "The bus stopped near the station",
    "My brother plays basketball every weekend",
    "She bought a new pair of shoes",
    "The stars shine brightly at night",
    "We watched the sunset together",
    "He opened the window slowly",
    "The garden is full of flowers",
    "I forgot my keys at home",
    "The computer is working perfectly",
    "She smiled at her best friend",
    "The children played in the yard",
    "Please close the window quietly",
    "The airplane landed safely",
    "I enjoy drinking hot tea",
    "The rabbit ran across the field",
    "My father drives to work daily",
    "The clock hangs on the wall",
    "We cleaned the room together",
    "The soup smells very good",
    "She carried the heavy bag carefully",
    "The boy kicked the ball hard",
    "Please answer the question honestly",
    "The library is very quiet",
    "I washed my hands before dinner",
    "The fish swims in the pond",
    "He repaired the old bicycle",
    "The family ate dinner together",
    "The stars covered the dark sky",
    "I found a coin on the ground",
    "The teacher wrote on the board",
    "She opened the gift happily",
    "The road leads to the village",
    "Please speak a little slower",
    "The horse jumped over the fence",
    "We enjoyed the school trip",
    "The doctor checked the patient carefully",
    "I heard a strange noise outside",
    "The lamp lights the entire room",
    "She folded the clothes neatly",
    "The students completed their homework",
    "The train moved very quickly",
    "I drank a cup of coffee",
    "The birds sang in the morning",
    "Please wait for me outside",
    "The mountain is covered with snow",
    "He cleaned the kitchen yesterday",
    "The little girl laughed loudly",
    "I need to charge my phone",

    "The farmer works in the field",
    "She baked a chocolate cake",
    "The wind blew through the trees",
    "I lost my notebook at school",
    "The waiter served the food quickly",
    "We walked along the beach",
    "The child drew a colorful picture",
    "He fixed the leaking pipe",
    "The room feels very cold",
    "I enjoy reading adventure stories",
    "The car stopped at the signal",
    "She watered the plants carefully",
    "The market opens early every morning",
    "Please bring me some water",
    "The students listened attentively",
    "I wore my favorite jacket today",
    "The lion rested under the tree",
    "He bought fresh vegetables yesterday",
    "The movie starts at seven tonight",
    "We visited our grandparents last weekend",
    "The baby cried during the night",
    "She cleaned the table after dinner",
    "The painter used bright colors",
    "I finished my homework early",
    "The mail arrived this afternoon",
    "Please turn down the television",
    "The children built a sandcastle",
    "He practiced the piano every evening",
    "The weather became colder suddenly",
    "I need to buy some bread",
    "The airplane flew above the clouds",
    "She opened the book carefully",
    "The river looks beautiful today",
    "We planted flowers in the garden",
    "The cat slept near the fireplace",
    "I heard birds outside my window",
    "The teacher asked an easy question",
    "Please keep the door closed",
    "The football match was exciting",
    "He carried the box upstairs",
    "The beach was crowded yesterday",
    "I wrote my name on the paper",
    "The train departed exactly on time",
    "She brushed her hair slowly",
    "The children sang a happy song",
    "We enjoyed the delicious meal",
    "The moon looked very bright tonight",
    "I opened my laptop to study",
    "The chef cooked pasta for dinner",
    "Please call me tomorrow morning",

    "The dog slept beside the sofa",
    "She packed her clothes neatly",
    "The classroom was very clean",
    "I saw a rainbow after the rain",
    "The boy climbed the tall tree",
    "We watched a funny movie",
    "The teacher collected the papers",
    "He closed the gate carefully",
    "The girl carried a pink backpack",
    "I need a new notebook",
    "The restaurant serves tasty food",
    "She learned to play the violin",
    "The workers built a strong bridge",
    "We stayed home during the storm",
    "The flowers smell wonderful today",
    "He sharpened the pencils quickly",
    "The students entered the classroom quietly",
    "I enjoy taking pictures outdoors",
    "The bus arrived late this morning",
    "Please write the answer clearly",
    "The baby smiled at her mother",
    "She placed the dishes on the table",
    "The football rolled across the grass",
    "We traveled to another city",
    "The man fixed the broken window",
    "I listened to music before sleeping",
    "The road was empty at night",
    "She tied her shoes tightly",
    "The waiter brought the menu quickly",
    "We sat near the fireplace",
    "The children danced at the party",
    "I found my wallet under the chair",
    "The sun disappeared behind the clouds",
    "He washed the car on Sunday",
    "The teacher explained the homework again",
    "Please open your textbook now",
    "The birds built a nest nearby",
    "I drank orange juice at breakfast",
    "The boy answered the question correctly",
    "She folded the letter carefully",
    "The computer screen is very bright",
    "We crossed the street carefully",
    "The rain continued throughout the day",
    "I cleaned my desk yesterday",
    "The family watched television together",
    "She bought fruit from the market",
    "The children ran around the playground",
    "Please keep your room tidy",
    "The train station was crowded",
    "I enjoyed the concert last night",

    "The puppy followed the boy home",
    "She wrote a message to her friend",
    "The baker made fresh bread today",
    "I opened the curtains this morning",
    "The school bus stopped outside",
    "He carried the groceries inside",
    "The garden looked beautiful after rain",
    "We played games during the trip",
    "The teacher read the story aloud",
    "I finished the project successfully",
    "The moon reflected on the water",
    "She organized her books carefully",
    "The children watched cartoons together",
    "Please clean the whiteboard after class",
    "The road became slippery after rain",
    "I packed my bag for school",
    "The singer performed beautifully tonight",
    "He answered the phone immediately",
    "The park was full of people",
    "We visited the zoo last summer",
    "The little boy lost his toy",
    "She painted the wall blue",
    "The airplane departed in the evening",
    "I listened carefully to the instructions",
    "The coffee smelled very strong",
    "The students prepared for the exam",
    "Please hand me the newspaper",
    "The train passed through the tunnel",
    "He fixed his watch yesterday",
    "The children enjoyed the magic show",
    "I placed the keys on the table",
    "The cat chased the small mouse",
    "She learned a new language quickly",
    "The doctor arrived at the hospital early",
    "We walked through the forest quietly",
    "The cake was decorated beautifully",
    "I checked my email this morning",
    "The stars disappeared behind the clouds",
    "Please lock the door before leaving",
    "The football player scored a goal",
    "She washed the dishes after dinner",
    "The river water feels very cold",
    "I bought a gift for my friend",
    "The students waited for the teacher",
    "The weather forecast predicted rain",
    "He carried his backpack to school",
    "The birds flew south for winter",
    "We enjoyed our vacation very much",
    "The child opened the present excitedly",
    "Please arrive before the meeting starts"
]

os.makedirs(OUTPUT_DIR, exist_ok=True)

for i, sentence in enumerate(SENTENCES):
    idx = f"sample{i+1:03d}"
    wav_path = os.path.join(OUTPUT_DIR, f"{idx}.wav")
    txt_path = os.path.join(OUTPUT_DIR, f"{idx}.txt")

    print(f"[{i+1}/{DATASET_SIZE}] Generating: {sentence}")

    tts = gTTS(text=sentence, lang="en", slow=False)
    mp3_path = os.path.join(OUTPUT_DIR, f"{idx}.mp3")
    tts.save(mp3_path)

    subprocess.run(
        [
            imageio_ffmpeg.get_ffmpeg_exe(),
            "-y", "-loglevel", "error",
            "-i", mp3_path,
            "-ar", str(SAMPLE_RATE),
            "-ac", "1",
            wav_path,
        ],
        check=True,
    )
    os.remove(mp3_path)

    with open(txt_path, "w") as f:
        f.write(sentence + "\n")

print(f"\nDone — {DATASET_SIZE} samples generated in {OUTPUT_DIR}/")
